### ISSUE TITLE
there is no code in the lib directory

### ISSUE THREAD

**Issue by zhoujianjack** [winstxnhdw/FullStanleyController#1]
Thank your for your work. I have a problem. After code download, there is no code in the lib directory. After manually finding the code from the modification record, it can't generate animation, it can display the predefined path map, maybe I'm not doing it right, can you update it, or tell me the more detailed requirement？

**Comment by winstxnhdw** [comment]
Hi @zhoujianjack,

There is no code because you did not install the submodules. As mentioned in the README file, you should be cloning the project recursively like so

```bash
git clone --recursive https://github.com/winstxnhdw/FullStanleyController.git
```

Let me know if this fixed the issue for you.
